"""empty message

Revision ID: 252ff18e6c04
Revises: d3b9d97d1042
Create Date: 2025-09-08 00:11:05.701442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252ff18e6c04'
down_revision = 'd3b9d97d1042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_user')
    # ### end Alembic commands ###
